version: '2'
run:
  modules-download-mode: readonly
output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gosec
    - govet
    - ineffassign
    - intrange
    - makezero
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 30
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - alfredoramos.mx/aur-pkg-helper
            - github.com/BurntSushi/toml
    errchkjson:
      check-error-free-encoding: false
      report-no-exported: true
    forbidigo:
      forbid:
        - pattern: ^(fmt\.Print(|f|ln)|print|println)$
          msg: Do not commit print statements
      analyze-types: true
    gosec:
      severity: medium
      confidence: medium
    govet:
      disable:
        - fieldalignment
        - nilness
      enable-all: true
    nestif:
      min-complexity: 7
    perfsprint:
      err-error: true
      strconcat: false
    prealloc:
      for-loops: true
    unused:
      field-writes-are-uses: false
      exported-fields-are-used: false
      parameters-are-used: false
      local-variables-are-used: false
      generated-is-used: false
    whitespace:
      multi-if: true
      multi-func: true
    sloglint:
      attr-only: true
      static-msg: true
      msg-style: capitalized
      key-naming-case: kebab
      args-on-sep-lines: true
      forbidden-keys:
        - time
        - level
        - msg
        - source
    misspell:
      locale: US
    nonamedreturns:
      report-error-in-defer: true
    predeclared:
      qualified-name: true
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-date-month: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true
      constant-kind: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      - linters:
          - cyclop
        path: (.+)_test\.go
      - linters:
          - staticcheck
        text: 'QF1008: could (remove embedded field|simplify selectors)'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
