version: '2'
run:
  modules-download-mode: readonly
output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoinits
    - gosec
    - makezero
    - musttag
    - nestif
    - nilerr
    - perfsprint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - unparam
    - whitespace
  settings:
    cyclop:
      max-complexity: 30
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - alfredoramos.mx/aur-pkg-helper
            - github.com/joho/godotenv
    errchkjson:
      check-error-free-encoding: false
      report-no-exported: true
    forbidigo:
      forbid:
        - pattern: ^(fmt\.Print(|f|ln)|print|println)$
          msg: Do not commit print statements
      analyze-types: true
    gosec:
      severity: medium
      confidence: medium
    govet:
      disable:
        - fieldalignment
        - nilness
      enable-all: true
    nestif:
      min-complexity: 8
    perfsprint:
      err-error: true
      strconcat: false
    prealloc:
      for-loops: true
    unused:
      field-writes-are-uses: false
      exported-fields-are-used: false
      parameters-are-used: false
      local-variables-are-used: false
      generated-is-used: false
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
